# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbtortPdj6OkQqfU44IQ87kLCcsadegs
"""

import librosa
import numpy as np
import joblib
import tensorflow as tf
from tensorflow.keras.models import load_model
from google.colab import drive
drive.mount('/content/drive')

def extract_features(file_path):
    y, sr = librosa.load(file_path, duration=3, offset=0.5)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    features = np.mean(mfcc, axis=1)  # shape: (40,)
    return features


# Load tools
model = load_model("/content/drive/MyDrive/Mars_dataset/best_model.h5")
encoder = joblib.load("/content/drive/MyDrive/Mars_dataset/label_encoder.pkl")
scaler = joblib.load("/content/drive/MyDrive/Mars_dataset/scaler.pkl")

# Test
file = "/content/drive/MyDrive/Mars_dataset/Sample_audio/anger.wav"  # Use a valid .wav file path here
features = extract_features(file).reshape(1, -1)
scaled = scaler.transform(features)
prediction = model.predict(scaled)
label = encoder.inverse_transform([np.argmax(prediction)])
print("Predicted Emotion:", label[0])

